version: '3.8'

services:
  db:
    image: postgres:15.5
    container_name: jiboong-postgres
    restart: always
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:5432"
    networks:
      - jiboong-network
    volumes:
      - ./.var/lib/postgresql/data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4-alpine
    container_name: jiboong-redis
    restart: always
    ports:
      - "17200:6379"
    networks:
      - jiboong-network
    volumes:
      - ./.var/lib/redis/data:/data

networks:
  jiboong-network:
    driver: bridge