server:
  port: ${SERVER_PORT}

spring:
  application:
    name: jiboong
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_schema: roof
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        mime:
          charset: UTF-8

  security:
    jwt:
      enabled: true
      subject: ${JWT_SUBJECT}
      access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRES_IN:PT15M}   # PT15M = 15 minutes
      refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRES_IN:P15D}  # P15D  = 15 days
      public-key: ${JWT_PUBLIC_KEY}
      private-key: ${JWT_PRIVATE_KEY}

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  use-fqn: true
  swagger-ui:
    display-request-duration: true
    defaultModelsExpandDepth: 10
    defaultModelExpandDepth: 10
    tags-sorter: alpha

path:
  web-resources:
    file: ${PATH_WEB_RESOURCES_FILE:}